#!/usr/bin/env python3

import argparse
import csv
from pathlib import Path


WORLD_MIN = 0.0
WORLD_MAX = 10.0
START = (1.0, 1.0)
GOAL = (9.0, 9.0)
OBSTACLES = (
    (5.0, 5.0, 1.25),
    (3.0, 6.5, 1.0),
    (7.0, 3.0, 1.0),
)


def read_path_csv(file_path):
    path_points = []

    with open(file_path, newline="") as csv_file:
        reader = csv.DictReader(csv_file)
        for row in reader:
            path_points.append((float(row["x"]), float(row["y"])))

    return path_points


def plot_scene(path_points, output_path=None):
    import matplotlib.pyplot as plt
    from matplotlib.patches import Circle

    figure, axes = plt.subplots(figsize=(7, 7))

    axes.set_title("2D OMPL Path")
    axes.set_xlabel("x")
    axes.set_ylabel("y")
    axes.set_xlim(WORLD_MIN, WORLD_MAX)
    axes.set_ylim(WORLD_MIN, WORLD_MAX)
    axes.set_aspect("equal", adjustable="box")
    axes.grid(True, linestyle="--", linewidth=0.5, alpha=0.5)

    for center_x, center_y, radius in OBSTACLES:
        obstacle = Circle(
            (center_x, center_y),
            radius,
            facecolor="tab:red",
            edgecolor="darkred",
            alpha=0.35,
            linewidth=1.5,
        )
        axes.add_patch(obstacle)

    if path_points:
        path_x = [point[0] for point in path_points]
        path_y = [point[1] for point in path_points]
        axes.plot(path_x, path_y, color="tab:blue", linewidth=2.0, label="Path")

    axes.scatter(*START, color="tab:green", s=80, label="Start", zorder=3)
    axes.scatter(*GOAL, color="tab:purple", s=80, label="Goal", zorder=3)
    axes.legend(loc="upper left")

    figure.tight_layout()

    if output_path:
        figure.savefig(output_path, dpi=160)
        print(f"Wrote plot image: {output_path}")
    else:
        plt.show()


def parse_args():
    parser = argparse.ArgumentParser(description="Plot a 2D OMPL path CSV with matplotlib.")
    parser.add_argument("path_csv", help="Path CSV generated by plan_2d.")
    parser.add_argument(
        "--output",
        "-o",
        help="Optional image output path. If omitted, an interactive plot window is shown.",
    )
    return parser.parse_args()


def main():
    args = parse_args()
    path_csv = Path(args.path_csv)

    if not path_csv.exists():
        raise FileNotFoundError(f"Path CSV does not exist: {path_csv}")

    output_path = Path(args.output) if args.output else None
    if output_path:
        import matplotlib

        matplotlib.use("Agg")

    path_points = read_path_csv(path_csv)
    plot_scene(path_points, output_path)


if __name__ == "__main__":
    main()
